name: event_ease
description: Event promotion app with venue booking.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'  # Fixed SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # UI & Styling
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  badges: ^3.0.0

  # Navigation & Routing
  go_router: ^15.1.1
  auto_route: ^9.3.0+1

  # Networking
  http: ^1.1.0
  dio: ^5.3.2
  retrofit: ^4.0.1
  logger: ^2.5.0

  # Data Persistence
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  cloud_firestore: ^5.6.7

  # Forms & Validation
  formz: ^0.8.0
  email_validator: ^3.0.0

  # Date & Time (using built-in picker)
  intl: ^0.20.2  # Keep this version for stability

  # Maps & Location
  google_maps_flutter: ^2.2.6
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # Animation
  flutter_animate: ^4.2.0
  lottie: ^3.3.1

  # Utilities
  uuid: ^4.5.1
  url_launcher: ^6.1.11
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4
  retrofit_generator: ^9.1.9
  auto_route_generator: ^9.0.0
  hive_generator: ^2.0.1
  mockito: ^5.4.0  # Keep this exact version